# Generated by Django 5.1.6 on 2025-06-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("easy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
